// vue/src/App.vue
<template>
  <h1>Nexys Vue Example</h1>
  <div class="btn-container">
    <button @click="clearLogs">Clear</button>
    <button @click="onLog">Test log</button>
    <button @click="onErrorLog">Error Log</button>
    <button @click="subscribe">Subscribe to "log.add"</button>
  </div>
</template>

<script lang="ts">
  import nexys from './nexys';

  export default {
    methods: {
      onLog() {
        // Log a message.
        nexys.log("Test log");
      },
      onErrorLog() {
        // Log an error.
        nexys.error({ message: "Test error log" });
      },
      subscribe() {
        // Subscribe to log.add
        nexys.Events.subscribe("log.add", (data) => {
          console.log("log added!", data);
        });
      },
      clearLogs() {
        // Clear logs and requests.
        nexys.clear();
      },

      // Read more about available functions: https://docs.nexys.app/category/functions
    },
  };
</script>

// react-native/App.tsx
import React from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  Text,
  TouchableOpacity,
  useColorScheme,
  View,
} from 'react-native';
import nexys from './nexys';
import type {PropsWithChildren} from 'react';

import {Colors} from 'react-native/Libraries/NewAppScreen';

function Button({onPress, children}: PropsWithChildren<{onPress: () => void}>) {
  return (
    <TouchableOpacity
      style={{padding: 8, backgroundColor: 'gray'}}
      onPress={onPress}>
      <Text style={{color: 'black'}}>{children}</Text>
    </TouchableOpacity>
  );
}

export default function App(): JSX.Element {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  function onLog() {
    // Log a message.
    nexys.log('Test log');
  }

  function onErrorLog() {
    // Log an error.
    nexys.error({message: 'Test error log'});
  }

  function subscribe() {
    // Subscribe to log.add
    nexys.Events.subscribe('log.add', data => {
      console.log('log added!', data);
    });
  }

  function clearLogs() {
    // Clear logs and requests.
    nexys.clear();
  }

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar
        barStyle={isDarkMode ? 'light-content' : 'dark-content'}
        backgroundColor={backgroundStyle.backgroundColor}
      />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        <View
          style={{
            flexDirection: 'column',
            gap: 4,
          }}>
          <Button onPress={clearLogs}>Clear</Button>
          <Button onPress={onLog}>Test log</Button>
          <Button onPress={onErrorLog}>Error log</Button>
          <Button onPress={subscribe}>Subscribe to "log.add"</Button>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
