// vue/src/App.vue
<template>
  <h1>Nexys Vue Example</h1>
  <div class="btn-container">
    <button @click="clearLogs">Clear</button>
    <button @click="onLog">Test log</button>
    <button @click="onErrorLog">Error Log</button>
    <button @click="subscribe">Subscribe to "log.add"</button>
  </div>
</template>

<script lang="ts">
  import nexys from './nexys';

  export default {
    methods: {
      onLog() {
        // Log a message.
        nexys.log("Test log");
      },
      onErrorLog() {
        // Log an error.
        nexys.error({ message: "Test error log" });
      },
      subscribe() {
        // Subscribe to log.add
        nexys.Events.subscribe("log.add", (data) => {
          console.log("log added!", data);
        });
      },
      clearLogs() {
        // Clear logs and requests.
        nexys.clear();
      },

      // Read more about available functions: https://docs.nexys.app/category/functions
    },
  };
</script>

// nextjs/src/app/page.tsx
"use client";
import "./style.css";
import nexys from "./nexys";

export default function Home() {
  function onLog() {
    // Log a message.
    nexys.log("Test log");
  }

  function onErrorLog() {
    // Log an error.
    nexys.error({ message: "Test error log" });
  }

  function subscribe() {
    // Subscribe to log.add
    nexys.Events.subscribe("log.add", (data) => {
      console.log("log added!", data);
    });
  }

  function clearLogs() {
    // Clear logs and requests.
    nexys.clear();
  }

  // Read more about available functions: https://docs.nexys.app/category/functions

  return (
    <div className="container">
      <h1>Nexys JavaScript Example</h1>
      <div className="btn-container">
        <button onClick={clearLogs}>Clear</button>
        <button onClick={onLog}>Test log</button>
        <button onClick={onErrorLog}>Error Log</button>
        <button onClick={subscribe}>Subscribe to "log.add"</button>
      </div>
    </div>
  );
}
